// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Menu
export const ERROR_DELETE_DISH = 'ERROR_DELETE_DISH';
export const ERROR_FETCH_DISHES = 'ERROR_FETCH_DISHES';
export const ERROR_FETCH_DISH = 'ERROR_FETCH_DISH';
export const ERROR_CREATE_DISH = 'ERROR_CREATE_DISH';
export const ERROR_UPDATE_DISH = 'ERROR_UPDATE_DISH';

export const RECEIVE_DISHES = 'RECEIVE_DISHES';
export const RECEIVE_DISH = 'RECEIVE_DISH';

export const REQUEST_DELETE_DISH = 'REQUEST_DELETE_DISH';
export const REQUEST_FETCH_DISHES = 'REQUEST_FETCH_DISHES';
export const REQUEST_FETCH_DISH = 'REQUEST_FETCH_DISH';
export const REQUEST_CREATE_DISH = 'REQUEST_CREATE_DISH';
export const REQUEST_UPDATE_DISH = 'REQUEST_UPDATE_DISH';

export const SUCCESS_DELETE_DISH = 'SUCCESS_DELETE_DISH';
export const SUCCESS_CREATE_DISH = 'SUCCESS_CREATE_DISH';
export const SUCCESS_UPDATE_DISH = 'SUCCESS_UPDATE_DISH';

// Category
export const ERROR_FETCH_CATEGORIES = 'ERROR_FETCH_CATEGORIES';

export const REQUEST_FETCH_CATEGORIES = 'REQUEST_FETCH_CATEGORIES';

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

